### ISSUE TITLE
Question 5: predicted probabilities plot 

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/PPOL5202_slides_activities#11]
![image](https://github.com/user-attachments/assets/acc33089-c89e-4fbb-b20c-d314852efb64)

**Comment by kloweth84** [comment]
Do we need to include year in the prediction analysis? The instructions say create a model using gender and aggressive variables but then it says to calculate the predicted probability of the tweet taking a denial stance for the following profiles at each of the years in the data.

**Comment by rebeccajohnson88** [comment]
> Do we need to include year in the prediction analysis? The instructions say create a model using gender and aggressive variables but then it says to calculate the predicted probability of the tweet taking a denial stance for the following profiles at each of the years in the data.

@kloweth84 sorry for the confusion! just predict for the combinations of gender and aggressiveness (so no need to include year in the model or prediction)
