### ISSUE TITLE
Question 1: part 3, count of precinct by counties

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/PPOL5202_slides_activities#14]
See below!

**Comment by rebeccajohnson88** [comment]
**Update:** we're currently double checking the above to make sure we have the correct number of precincts per county!

**Comment by JiaqinWu** [comment]
![image](https://github.com/user-attachments/assets/72013196-8440-4955-9057-8c045701628e)

**Comment by JiaqinWu** [comment]
When using st_join(), ensure the following steps for accurate results:
1. Ensure Unique Values: Check for uniqueness in the key columns of both datasets. If necessary, clean and standardize values to avoid mismatches during the join.
2. Clean Data: Before joining, perform data cleaning—this includes trimming whitespace, resolving name inconsistencies, and ensuring key columns match.
3. Check CRS Consistency: Make sure both datasets have the same Coordinate Reference System (CRS). Use st_crs() to verify and st_transform() to align them if needed.
4. Verify Data Shapes: After the join, check the shape of the resulting dataframe to confirm it aligns with expectations. This helps catch issues like duplicated rows or unexpected geometries.
