### ISSUE TITLE
Question 4: ROC curve

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/PPOL5202_slides_activities#9]
![image](https://github.com/user-attachments/assets/a219bc74-151b-4d2f-bc0c-fe561306de83)

**Comment by aasthajha98** [comment]
I am having trouble extracting out just the predictions from the random forest, there's a random string in the middle of the predictions when I try and turn the factor into a dataframe to isolate just the prediction values.

**Comment by rebeccajohnson88** [comment]
> I am having trouble extracting out just the predictions from the random forest, there's a random string in the middle of the predictions when I try and turn the factor into a dataframe to isolate just the prediction values.

I would break this down into two steps:

1. Use the `predict` command alone with the model + the test_data to predict in the test set
2. You should be able to extract the predictions from the result of step 1

Let us know if still questions after trying that!
